stages:
  - retrain
  - build
  - test
  - deploy

retrain_model:
  stage: retrain
  image: python:3.8
  script:
    # Install Azure CLI and ML extension
    - pip install azure-cli
    - az extension add -n ml -y

    # Login to Azure
    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"

    # Register/Update environments
    - az ml environment create --file environment/dataprep-env.yaml --resource-group $AZURE_RESOURCE_GROUP --workspace-name $AZURE_WORKSPACE
    - az ml environment create --file environment/tensorflow.yaml --resource-group $AZURE_RESOURCE_GROUP --workspace-name $AZURE_WORKSPACE

    # Register/Update compute (will not fail if already exists)
    - az ml compute create --file environment/compute.yaml --resource-group $AZURE_RESOURCE_GROUP --workspace-name $AZURE_WORKSPACE || true
    - az ml compute start --name project-ml-compute --resource-group $AZURE_RESOU_GROUP --workspace-name $AZURE_WORKSPACE || true    
    # Register/Update components
    - az ml component create --file components/dataprep/dataprep.yaml --resource-group $AZURE_RESOURCE_GROUP --workspace-name $AZURE_WORKSPACE
    - az ml component create --file components/training/training.yaml --resource-group $AZURE_RESOURCE_GROUP --workspace-name $AZURE_WORKSPACE

    # Submit pipeline job
    - az ml job create --file pipelines/pipeline.yaml --resource-group $AZURE_RESOURCE_GROUP --workspace-name $AZURE_WORKSPACE

  only:
    - main  # Or your default branch

variables:
  REGISTRY: "registry.gitlab.com/luka.chiapponi/mlops-project"
  NAMESPACE: "mlops"

build-images:
  stage: build
  script:
    - docker build -t $REGISTRY/housing-api:$CI_COMMIT_SHA ./api
    - docker build -t $REGISTRY/housing-frontend:$CI_COMMIT_SHA ./frontend
    - docker build -t $REGISTRY/housing-nginx:$CI_COMMIT_SHA ./nginx
    - docker push $REGISTRY/housing-api:$CI_COMMIT_SHA
    - docker push $REGISTRY/housing-frontend:$CI_COMMIT_SHA
    - docker push $REGISTRY/housing-nginx:$CI_COMMIT_SHA
  only:
    - main

deploy-to-k8s:
  stage: deploy
  script:
    - cd docker
    - export TAG=$CI_COMMIT_SHA
    - export REGISTRY=$REGISTRY
    - chmod +x build-and-deploy.sh
    - ./build-and-deploy.sh
  only:
    - main
  when: manual