apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-api
  namespace: housing-app
  labels:
    app: housing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: housing-api
  template:
    metadata:
      labels:
        app: housing-api
    spec:
      containers:
      - name: housing-api
        image: housing-api:latest  # Fixed: removed your-registry.com
        imagePullPolicy: IfNotPresent  # Changed from Always to IfNotPresent for local images
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/app/trained_model.h5"
        # Removed ConfigMap reference since it doesn't exist
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      # Removed volumes section since ConfigMap doesn't exist
---
apiVersion: v1
kind: Service
metadata:
  name: housing-api-service
  namespace: housing-app
spec:
  selector:
    app: housing-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP