apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-frontend
  namespace: housing-app
  labels:
    app: housing-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: housing-frontend
  template:
    metadata:
      labels:
        app: housing-frontend
    spec:
      containers:
      - name: housing-frontend
        image: housing-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: housing-frontend-service
  namespace: housing-app
spec:
  selector:
    app: housing-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP