apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-api
  labels:
    app: housing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: housing-api
  template:
    metadata:
      labels:
        app: housing-api
    spec:
      containers:
      - name: housing-api
        image: your-registry.com/housing-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/app/trained_model.h5"
        - name: MODEL_VERSION
          valueFrom:
            configMapKeyRef:
              name: model-config
              key: version
              optional: true
        volumeMounts:
        - name: model-volume
          mountPath: /app/trained_model.h5
          subPath: trained_model.h5
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: model-volume
        configMap:
          name: model-config
---
apiVersion: v1
kind: Service
metadata:
  name: housing-api-service
spec:
  selector:
    app: housing-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP